//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SimpleWebForm.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;




    public partial class UserCredit
    {
        [Required(ErrorMessage = "A Unique UserId / UserName is required")]
        [StringLength(50, MinimumLength = 5, ErrorMessage = "Invalid User, must be at lease 5 characters")]
        [Display(Name = "User Name / User Id")]
        public string UserId { get; set; }
        [Required(ErrorMessage = "A default Credit Amount is required")]
        [Range(0, int.MaxValue, ErrorMessage = "Please enter valid integer Number")]
        //[RegularExpression("^[0-9]", ErrorMessage = "Numeric Value Please")]
        //[Range(0, 10)]
        public int Credits { get; set; }
    }
}
